# Generated by Django 3.2.9 on 2021-12-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='liker',
        ),
    ]
