# Generated by Django 3.2.9 on 2021-12-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_user_likes_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
